app_home:
    path: /
    controller: App\Controller\HomeController::home

app_portfolios:
    path: /portfolios
    controller: App\Controller\HomeController::portfolios

app_portfolio_delete:
    path: /portfolio/{portfolioId}/delete
    controller: App\Controller\HomeController::deletePortfolio
