app_home:
    path: /
    controller: App\Controller\HomeController::home

app_positions:
    path: /positions
    controller: App\Controller\HomeController::positions

app_portfolio_delete:
    path: /portfolio/{portfolioId}/delete
    controller: App\Controller\HomeController::deletePortfolio
